@url = "http://localhost:3000"

GET http://localhost:3000 HTTP/1.1

###

POST http://localhost:3000/flights HTTP/1.1 

Content-Type: application/json  
{
"from": "Nigeria",
"to": "canada",
"date": "12-08-2022",
"promo": "15189"
}

###

 GET http://localhost:3000/flights/af8f5ba7-5dfa-4514-8e83-7bb7f600ea05 HTTP/1.1